# permissions for end users to view opcuaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: opcuaserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orca-opcua-server
    app.kubernetes.io/part-of: orca-opcua-server
    app.kubernetes.io/managed-by: kustomize
  name: opcuaserver-viewer-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - opcuaservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - opcuaservers/status
  verbs:
  - get
